"""(Re)deploy the Hugging Face Space that runs the API.

The Space is fully generated: a README (Space metadata) + a one-line Dockerfile that pulls
the serving image from GHCR and points it at the published model repo. Run by the
`deploy-space` CI job on every `v*` tag; can also be run by hand.

Usage:
    HF_TOKEN=... python -m src.deploy_space --image ghcr.io/mateplo/mlops-project-m1:1.0.0
"""

from __future__ import annotations

import argparse
import logging
import os
import tempfile
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
logging.basicConfig(level="INFO", format="%(asctime)s %(levelname)-7s %(name)s: %(message)s")
log = logging.getLogger("deploy_space")


def load_config(path: str | Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def read_env_file(path: Path) -> dict[str, str]:
    env = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def render_dockerfile(image: str, model_repo: str, env: dict[str, str]) -> str:
    lines = [
        "# Generated by src/deploy_space.py — do not edit here, open a PR on GitHub.",
        f"FROM {image}",
        f'ENV MODEL_REPO="{model_repo}"',
    ]
    for k, v in env.items():
        lines.append(f'ENV {k}="{v}"')
    lines.append("EXPOSE 8000")
    return "\n".join(lines) + "\n"


def deploy(cfg: dict, image: str, space: str | None = None, token: str | None = None) -> str:
    from huggingface_hub import HfApi

    token = token or os.getenv("HF_TOKEN")
    if not token:
        raise SystemExit("HF_TOKEN is not set (needs a write token).")
    space = space or os.getenv("HF_SPACE_REPO") or cfg["hf"]["space_repo"]
    model_repo = os.getenv("HF_MODEL_REPO") or cfg["hf"]["model_repo"]
    env = read_env_file(PROJECT_ROOT / "deploy" / "space.env")

    api = HfApi(token=token)
    revision = env.get("MODEL_REVISION", "main")
    api.create_repo(space, repo_type="space", space_sdk="docker", exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        d = Path(tmp)
        (d / "README.md").write_text((PROJECT_ROOT / "deploy" / "space" / "README.md").read_text())
        (d / "Dockerfile").write_text(render_dockerfile(image, model_repo, env))
        api.upload_folder(
            repo_id=space,
            repo_type="space",
            folder_path=tmp,
            commit_message=f"Deploy {image} (model {model_repo}@{revision})",
        )
    url = f"https://huggingface.co/spaces/{space}"
    log.info("deployed %s -> %s", image, url)
    return url


def main() -> None:
    parser = argparse.ArgumentParser(description="Deploy the API to a HF Space")
    parser.add_argument("--config", default="configs/config.yaml")
    parser.add_argument(
        "--image", required=True, help="full image reference, e.g. ghcr.io/owner/repo:1.0.0"
    )
    parser.add_argument(
        "--space", default=None, help="owner/name (default: hf.space_repo in config)"
    )
    args = parser.parse_args()
    deploy(load_config(args.config), args.image, args.space)


if __name__ == "__main__":
    main()
