"""Publish the exported champion (artifacts/) to a Hugging Face model repo.

MLflow stays the registry (tracking + promotion); the HF model repo is the *distribution*
channel the serving image downloads from. Each publish creates a commit on `main` and a
tag `v<registry version>`, so a Space can pin an exact registry version.

Usage:
    HF_TOKEN=... python -m src.publish --config configs/config.yaml [--repo owner/name]
"""

from __future__ import annotations

import argparse
import os

from src.meta import META_FILENAME, read_meta
from src.utils import get_logger, load_config, resolve

log = get_logger(__name__)


def model_card(meta: dict, github_repo: str = "mateplo/MLOps-project-M1") -> str:
    m = meta.get("metrics", {})
    rows = "\n".join(
        f"| {k} | {v:.4f} |"
        for k, v in m.items()
        if isinstance(v, (int, float)) and k != "decision_threshold"
    )
    return f"""---
library_name: sklearn
tags: [tabular-classification, adult-income, mlflow, mlops]
license: mit
---

# Adult Income Classifier — published champion

Generated by `make publish-model` from [{github_repo}](https://github.com/{github_repo}).
**Do not edit by hand**: the source of truth is the MLflow registry of that project.

| | |
|---|---|
| Registry model | `{meta.get("model_name")}` |
| Registry version | **{meta.get("version")}** ({meta.get("alias")}) |
| MLflow run_id | `{meta.get("run_id")}` |
| Model type | {meta.get("model_type")} |
| Decision threshold | {float(meta.get("decision_threshold", 0.5)):.4f} |
| Training data sha256 | `{meta.get("data_sha256")}` |
| Trained at | {meta.get("trained_at")} |

## Held-out test metrics

| metric | value |
|---|---|
{rows}

## Files

- `model.joblib`: scikit-learn Pipeline (preprocessing + classifier)
- `model_meta.json`: identity + threshold consumed by the API (`/health` exposes it)
"""


def publish(
    cfg: dict, repo: str | None = None, token: str | None = None, private: bool = False
) -> dict:
    from huggingface_hub import HfApi

    token = token or os.getenv("HF_TOKEN")
    if not token:
        raise SystemExit("HF_TOKEN is not set (needs a write token).")
    repo = repo or os.getenv("HF_MODEL_REPO") or cfg["hf"]["model_repo"]
    art_dir = resolve(cfg["artifacts"]["dir"])
    meta = read_meta(art_dir / META_FILENAME)
    if not meta.get("version"):
        raise SystemExit("artifacts/model_meta.json has no version: run `make export` first.")
    if meta.get("alias") != cfg["mlflow"].get("champion_alias", "champion"):
        raise SystemExit(f"refusing to publish a non-champion model (alias={meta.get('alias')!r}).")

    api = HfApi(token=token)
    api.create_repo(repo, repo_type="model", private=private, exist_ok=True)
    card_path = art_dir / "README.md"
    card_path.write_text(model_card(meta))
    tag = f"v{meta['version']}"
    commit = api.upload_folder(
        repo_id=repo,
        repo_type="model",
        folder_path=str(art_dir),
        allow_patterns=["model.joblib", META_FILENAME, "README.md"],
        commit_message=f"Publish registry version {meta['version']} (run {meta['run_id'][:8]})",
    )
    existing = {t.name for t in api.list_repo_refs(repo, repo_type="model").tags}
    if tag in existing:
        api.delete_tag(repo, tag=tag, repo_type="model")
    api.create_tag(repo, tag=tag, repo_type="model", tag_message=f"MLflow run {meta['run_id']}")
    url = f"https://huggingface.co/{repo}"
    log.info("published v%s -> %s (tag %s, commit %s)", meta["version"], url, tag, commit.oid[:8])
    return {"repo": repo, "url": url, "tag": tag, "version": meta["version"], "commit": commit.oid}


def main() -> None:
    parser = argparse.ArgumentParser(description="Publish the exported champion to the HF Hub")
    parser.add_argument("--config", default="configs/config.yaml")
    parser.add_argument(
        "--repo", default=None, help="owner/name (default: hf.model_repo in config)"
    )
    parser.add_argument("--private", action="store_true")
    args = parser.parse_args()
    publish(load_config(args.config), args.repo, private=args.private)


if __name__ == "__main__":
    main()
